title: Guillaume P. Pech
description: Cognitive Science of volition, agency, and decision-making
theme: jekyll-theme-minimal
logo: /portrait.jpg
show_downloads: false
github:
  is_project_page: false
